#!/usr/bin/env python3
"""Render the Apple Private Relay catalogue-churn time-series figure.

The plot reads the CSV generated by ``churn_series.py``.  It keeps address
families separate, shows removed CIDR records below zero, and shades observation
intervals longer than one calendar day.

Outputs by default:
  catalogue_churn_timeline.pdf  (vector PDF with embedded TrueType fonts)
  catalogue_churn_timeline.png  (600 dpi inspection image)
"""

from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402


IPV4_BLUE = "#0072B2"
IPV6_GREEN = "#009E73"
REMOVE_VERMILLION = "#D55E00"
LABEL_PURPLE = "#7A5195"
LABEL_GOLD = "#E69F00"
CHARCOAL = "#2F2F2F"
AXIS_GREY = "#777777"
GRID_GREY = "#E5E5E5"

COUNT_FIELDS = ("added_pfx", "removed_pfx", "reassign_count")
REQUIRED_FIELDS = {
    "date_from",
    "date_to",
    "interval_days",
    "family",
    *COUNT_FIELDS,
}


@dataclass(frozen=True)
class Interval:
    """One observed snapshot-to-snapshot comparison interval."""

    date_from: date
    date_to: date
    interval_days: int


@dataclass
class ChurnSeries:
    """Plot-ready churn counts, keyed by address family and interval end date."""

    intervals: list[Interval]
    values: dict[str, dict[date, dict[str, int]]]


def load_series(path: str | Path) -> ChurnSeries:
    """Load and validate a ``churn_series.py`` output file.

    The loader permits a file containing only one family, but rejects duplicate
    family/date rows and date or interval metadata that could silently distort
    the x-axis or the gap shading.
    """
    intervals_by_end: dict[date, Interval] = {}
    values: dict[str, dict[date, dict[str, int]]] = {"v4": {}, "v6": {}}

    with Path(path).open(newline="") as source:
        reader = csv.DictReader(source)
        header = set(reader.fieldnames or [])
        missing_fields = REQUIRED_FIELDS - header
        if missing_fields:
            missing = ", ".join(sorted(missing_fields))
            raise ValueError(f"missing required churn-series columns: {missing}")

        for line_number, row in enumerate(reader, start=2):
            try:
                date_from = date.fromisoformat(row["date_from"])
                date_to = date.fromisoformat(row["date_to"])
                interval_days = int(row["interval_days"])
                metrics = {field: int(row[field]) for field in COUNT_FIELDS}
            except (TypeError, ValueError) as error:
                raise ValueError(f"invalid churn-series row {line_number}: {error}") from error

            family = row["family"]
            if family not in values:
                raise ValueError(f"invalid address family at row {line_number}: {family!r}")
            if interval_days <= 0 or (date_to - date_from).days != interval_days:
                raise ValueError(
                    f"invalid interval metadata at row {line_number}: "
                    f"{date_from} -> {date_to} ({interval_days})"
                )
            if any(value < 0 for value in metrics.values()):
                raise ValueError(f"negative churn count at row {line_number}")

            interval = Interval(date_from, date_to, interval_days)
            existing_interval = intervals_by_end.setdefault(date_to, interval)
            if existing_interval != interval:
                raise ValueError(f"inconsistent interval ending {date_to} at row {line_number}")
            if date_to in values[family]:
                raise ValueError(f"duplicate {family} row ending {date_to} at row {line_number}")
            values[family][date_to] = metrics

    intervals = sorted(intervals_by_end.values(), key=lambda item: item.date_to)
    if not intervals:
        raise ValueError("churn-series CSV contains no observations")
    return ChurnSeries(intervals=intervals, values=values)


def configure_matplotlib() -> None:
    matplotlib.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.family": "serif",
            "font.serif": ["DejaVu Serif"],
            "font.size": 8.5,
            "text.color": CHARCOAL,
            "axes.labelcolor": CHARCOAL,
            "xtick.color": CHARCOAL,
            "ytick.color": CHARCOAL,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )


def family_values(series: ChurnSeries, family: str, field: str, *, sign: int = 1) -> list[int] | None:
    """Return one family/field at every observed interval, or ``None`` if absent."""
    family_rows = series.values[family]
    if not family_rows:
        return None
    return [sign * family_rows.get(interval.date_to, {}).get(field, 0) for interval in series.intervals]


def plot_series(
    ax,
    dates: list[date],
    values: list[int],
    *,
    label: str,
    color: str,
    marker_size: float,
    marker_face: str,
    zorder: int,
    linestyle: str = "-",
) -> None:
    """Plot every observation, including zero-valued intervals."""
    ax.plot(
        dates,
        values,
        color=color,
        linestyle=linestyle,
        linewidth=0.85,
        marker="o",
        markersize=marker_size,
        markerfacecolor=marker_face,
        markeredgecolor=color,
        markeredgewidth=0.75,
        label=label,
        zorder=zorder,
    )


def annotate_nonzero(
    ax,
    dates: list[date],
    values: list[int],
    *,
    kind: str,
    color: str,
) -> None:
    """Label non-zero observations using values sourced from the input CSV."""
    final_date = dates[-1]
    for event_date, value in zip(dates, values):
        if value == 0:
            continue
        if kind == "added":
            text = f"+{value}"
        elif kind == "removed":
            text = f"−{abs(value)}"
        else:
            text = str(value)

        x_offset = -5 if event_date == final_date else 0
        horizontal_alignment = "right" if event_date == final_date else "center"
        if value < 0:
            y_offset = -11
            vertical_alignment = "top"
        elif value >= 100:
            x_offset = -6
            y_offset = 0
            horizontal_alignment = "right"
            vertical_alignment = "center"
        else:
            y_offset = 7
            vertical_alignment = "bottom"

        ax.annotate(
            text,
            xy=(event_date, value),
            xytext=(x_offset, y_offset),
            textcoords="offset points",
            ha=horizontal_alignment,
            va=vertical_alignment,
            fontsize=7.2,
            color=color,
            fontweight="bold",
            clip_on=False,
            zorder=8,
        )


def shade_multi_day_gaps(ax, intervals: list[Interval]) -> None:
    """Make non-consecutive snapshots visible without inventing missing values."""
    for interval in intervals:
        if interval.interval_days > 1:
            ax.axvspan(
                interval.date_from,
                interval.date_to,
                color=AXIS_GREY,
                alpha=0.08,
                linewidth=0,
                zorder=0,
            )


def style_axis(ax) -> None:
    ax.grid(axis="y", color=GRID_GREY, linewidth=0.65)
    ax.set_axisbelow(True)
    ax.tick_params(axis="both", labelsize=7.7, width=0.7, color=AXIS_GREY)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS_GREY)
        ax.spines[side].set_linewidth(0.7)


def set_dynamic_ylim(ax, values: list[list[int]], *, include_zero: bool = True) -> None:
    """Use a small data-dependent margin while retaining a readable zero line."""
    observed = [value for series in values for value in series]
    if include_zero:
        observed.append(0)
    lower, upper = min(observed), max(observed)
    if lower == upper:
        upper = lower + 1
    padding = max(1, (upper - lower) * 0.1)
    ax.set_ylim(lower - padding, upper + padding)


def build_figure(series: ChurnSeries):
    """Build the fixed-style, data-driven two-panel churn figure."""
    configure_matplotlib()
    fig, (top_ax, bottom_ax) = plt.subplots(
        2,
        1,
        figsize=(7.1, 4.9),
        sharex=True,
        gridspec_kw={"height_ratios": [1.08, 1.0]},
    )
    fig.subplots_adjust(left=0.13, right=0.975, top=0.97, bottom=0.13, hspace=0.17)
    dates = [interval.date_to for interval in series.intervals]

    top_values: list[list[int]] = []
    bottom_values: list[list[int]] = []
    for family, color, marker_size in (("v4", IPV4_BLUE, 2.6), ("v6", IPV6_GREEN, 3.9)):
        label = f"IPv{family[-1]} CIDRs added"
        values = family_values(series, family, "added_pfx")
        if values is not None:
            plot_series(
                top_ax, dates, values, label=label, color=color, marker_size=marker_size,
                marker_face=color, zorder=4,
            )
            annotate_nonzero(top_ax, dates, values, kind="added", color=color)
            top_values.append(values)

        removed = family_values(series, family, "removed_pfx", sign=-1)
        if removed is not None:
            plot_series(
                top_ax, dates, removed, label=f"IPv{family[-1]} CIDRs removed",
                color=REMOVE_VERMILLION, marker_size=marker_size + 1.1,
                marker_face="white", zorder=2, linestyle="--",
            )
            annotate_nonzero(top_ax, dates, removed, kind="removed", color=REMOVE_VERMILLION)
            top_values.append(removed)

    top_ax.axhline(0, color=AXIS_GREY, linewidth=0.8, zorder=1)
    top_ax.set_ylabel("Change in CIDR records", labelpad=7)
    set_dynamic_ylim(top_ax, top_values)
    if top_ax.lines[:-1]:
        top_ax.legend(loc="upper left", ncol=2, frameon=False, fontsize=7.4,
                      handlelength=1.8, columnspacing=1.4)

    for family, color, marker_size in (("v4", LABEL_PURPLE, 4.0), ("v6", LABEL_GOLD, 2.7)):
        values = family_values(series, family, "reassign_count")
        if values is None:
            continue
        plot_series(
            bottom_ax, dates, values, label=f"IPv{family[-1]} label-change runs",
            color=color, marker_size=marker_size,
            marker_face="white" if family == "v4" else color, zorder=3,
        )
        annotate_nonzero(bottom_ax, dates, values, kind="label", color=color)
        bottom_values.append(values)

    bottom_ax.set_ylabel("Label-change runs", labelpad=7)
    bottom_ax.set_xlabel("Interval end date", labelpad=7)
    set_dynamic_ylim(bottom_ax, bottom_values)
    if bottom_ax.lines:
        bottom_ax.legend(loc="upper left", ncol=2, frameon=False, fontsize=7.4,
                         handlelength=1.8, columnspacing=1.6)

    for ax in (top_ax, bottom_ax):
        shade_multi_day_gaps(ax, series.intervals)
        style_axis(ax)

    locator = mdates.AutoDateLocator(minticks=6, maxticks=10, interval_multiples=True)
    bottom_ax.xaxis.set_major_locator(locator)
    bottom_ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(locator))
    bottom_ax.set_xlim(series.intervals[0].date_from, series.intervals[-1].date_to)
    return fig


def save_figure(fig, pdf_path: str | Path, png_path: str | Path) -> None:
    """Write stable figure metadata so reruns are not timestamp-dependent."""
    attribution = "iCPR egress-catalogue reproducibility pipeline"
    fig.savefig(
        pdf_path,
        metadata={
            "Creator": attribution,
            "Producer": attribution,
            "CreationDate": None,
            "ModDate": None,
        },
    )
    fig.savefig(png_path, dpi=600, metadata={"Software": attribution})


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render the Apple Private Relay catalogue-churn time series"
    )
    parser.add_argument(
        "--csv",
        default="churn_series.csv",
        help="input written by churn_series.py (default: %(default)s)",
    )
    parser.add_argument("--pdf", default="catalogue_churn_timeline.pdf", help="vector PDF output path")
    parser.add_argument("--png", default="catalogue_churn_timeline.png", help="600 dpi PNG output path")
    args = parser.parse_args()

    try:
        series = load_series(args.csv)
    except (OSError, ValueError) as error:
        raise SystemExit(f"error: {error} (run churn_series.py first)") from error

    fig = build_figure(series)
    save_figure(fig, args.pdf, args.png)
    plt.close(fig)
    print(f"wrote {args.pdf} (vector PDF)")
    print(f"wrote {args.png} (600 dpi PNG)")


if __name__ == "__main__":
    main()
